package com.nahmed.enums;

public enum ConfigProperties {

    ENVIRONMENT, BASE_URL, TOKEN_URL, CLIENT_ID, CLIENT_SECRET,
    DATAPROVIDER_THREAD_COUNT, USERNAME, PASSWORD, INVALID_TOKEN, EXPIRED_TOKEN;

}
